export const statusConfig = {
  submitted: {
    label: 'Submitted',
    gaugeColor: '#0F2E35',
    badgeBg: 'bg-deep-800',
    badgeText: 'text-white',
    dot: 'bg-deep-500',
    adminBg: 'bg-deep-800',
    adminText: 'text-white',
  },
  acknowledged: {
    label: 'Acknowledged',
    gaugeColor: '#127A7A',
    badgeBg: 'bg-teal-600',
    badgeText: 'text-white',
    dot: 'bg-teal-500',
    adminBg: 'bg-teal-600',
    adminText: 'text-white',
  },
  in_progress: {
    label: 'In Progress',
    gaugeColor: '#C8914A',
    badgeBg: 'bg-brass-400',
    badgeText: 'text-white',
    dot: 'bg-brass-500',
    adminBg: 'bg-brass-400',
    adminText: 'text-white',
  },
  resolved: {
    label: 'Resolved',
    gaugeColor: '#2E7D5A',
    badgeBg: 'bg-resolved',
    badgeText: 'text-white',
    dot: 'bg-success-500',
    adminBg: 'bg-resolved',
    adminText: 'text-white',
  },
  rejected: {
    label: 'Rejected',
    gaugeColor: '#C44A3A',
    badgeBg: 'bg-emergency',
    badgeText: 'text-white',
    dot: 'bg-danger-500',
    adminBg: 'bg-emergency',
    adminText: 'text-white',
  },
}
